### ISSUE TITLE
Children passed to background component do not update

### ISSUE THREAD

**Issue by JosephMarotte** [imgix/react-imgix#789]
**Before you submit:**

- [x] Please search through the existing issues (both open AND closed) to see if your issue has been discussed before. Github issue search can be used for this: https://github.com/imgix/react-imgix/issues?utf8=%E2%9C%93&q=is%3Aissue
- [x] Please ensure the problem has been isolated and reduced. This link explains more: http://css-tricks.com/6263-reduced-test-cases/

**Describe the bug**
`Background` component do not update although I believe it should.

**To Reproduce**

Link to sandbox : https://codesandbox.io/s/musing-cray-w6tel?file=/src/App.js

Code sample :
```js
import { Background } from 'react-imgix';
import React, { useState } from 'react';
 
export default function App() {
  const [counter, setCounter] = useState(0);
  return (
    <>
    <Background 
    src="https://images.prismic.io/slicemachine-blank/30d6602b-c832-4379-90ef-100d32c5e4c6_selfie.png?auto=compress,format">
      {counter}
    </Background>
    {counter}
    <button onClick={() => setCounter(counter + 1)}>increment counter</button>
    </>
  );
}
```

Steps to reproduce the behaviour:

1.  Go to https://codesandbox.io/s/musing-cray-w6tel?file=/src/App.js
2.  Click on `Increment counter` button
3.  See error

**Expected behaviour**
React children props passed to `Background` component should update.

**Information:**

- react-imgix version: 9.1.1
- browser version: whatsmybrowser.org/b/ZKTOF

**Additional context**
I think the problem lies with the following lines of `react-img-bg.jsx` :
https://github.com/imgix/react-imgix/blob/main/src/react-imgix-bg.jsx#L50-L60

```js
    // If we made it here, we need to check if the "top-level"    
    // props have changed (e.g. disableLibraryParam).
     const shallowPropsEqual = shallowEqual(this.props, nextProps);
    // We also need to check the imgixParams.
    const shallowParamsEqual = shallowEqual(this.props.imgixParams, nextProps.imgixParams);
    return shallowPropsEqual && shallowParamsEqual;
 ```
 
 The return statement should be `!(shallowPropsEqual && shallowParamsEqual)`

**Comment by frederickfogerty** [comment]
Hey @JosephMarotte 👋 thanks for opening the detailed bug report and sorry that you had an issue here! We've allotted some time to look at this on Thursday next week so hopefully should be able to to release a fix shortly after that! Until then, I would suggest as a workaround to rollback to the previous react-imgix version.

**Comment by luqven** [comment]
Hey @JosephMarotte, 

We've just opened a PR #793 that should fix the issue where the child components were not updating. Once the fix is merged in and released, we'll circle back to let you know and close this issue.

Thanks again for taking the time to report the bug  🌟

**Comment by JosephMarotte** [comment]
Hello @luqven,
To me it seems there are still some kind of an issue.
I updated react-imgix to 9.1.3 on the sandbox (https://codesandbox.io/s/musing-cray-w6tel?file=/src/App.js) but the problem is still here. And when updating to the latest version on my computer, looking at the code in node_modules the fix does not seems to be there, maybe I am missing something ?

Looking at https://github.com/imgix/react-imgix/commit/eefb6eda132b394dfdffd0f9beadfe410c8593d0 it seems the value of 
`export const PACKAGE_VERSION = "9.1.2";` in `src/constants.js` was not updated to 9.1.3
The travis job also failed so maybe it’s the reason why.

**Comment by luqven** [comment]
> Looking at [eefb6ed](https://github.com/imgix/react-imgix/commit/eefb6eda132b394dfdffd0f9beadfe410c8593d0) it seems the value of
> `export const PACKAGE_VERSION = "9.1.2";` in `src/constants.js` was not updated to 9.1.3

@JosephMarotte 💯  

There was a build issue with `9.1.3`. We've just released `9.1.4`. If you update your dependencies in the sandbox you link above to `9.1.4`, you should see the child components updating.

Thanks again for reporting the issue and should anything else come up please let us know.
